// Code generated by protoc-gen-go. DO NOT EDIT.
// source: guest.proto

package protoGuest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Guest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ratio                float32  `protobuf:"fixed32,2,opt,name=ratio,proto3" json:"ratio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Guest) Reset()         { *m = Guest{} }
func (m *Guest) String() string { return proto.CompactTextString(m) }
func (*Guest) ProtoMessage()    {}
func (*Guest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f02ef301e169e63, []int{0}
}

func (m *Guest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Guest.Unmarshal(m, b)
}
func (m *Guest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Guest.Marshal(b, m, deterministic)
}
func (m *Guest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Guest.Merge(m, src)
}
func (m *Guest) XXX_Size() int {
	return xxx_messageInfo_Guest.Size(m)
}
func (m *Guest) XXX_DiscardUnknown() {
	xxx_messageInfo_Guest.DiscardUnknown(m)
}

var xxx_messageInfo_Guest proto.InternalMessageInfo

func (m *Guest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Guest) GetRatio() float32 {
	if m != nil {
		return m.Ratio
	}
	return 0
}

func init() {
	proto.RegisterType((*Guest)(nil), "protoGuest.Guest")
}

func init() { proto.RegisterFile("guest.proto", fileDescriptor_4f02ef301e169e63) }

var fileDescriptor_4f02ef301e169e63 = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2f, 0x4d, 0x2d,
	0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x53, 0xee, 0x20, 0x11, 0x25, 0x43,
	0x2e, 0x56, 0x30, 0x43, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xcc, 0x16, 0x12, 0xe1, 0x62, 0x2d, 0x4a, 0x2c, 0xc9, 0xcc, 0x97, 0x60, 0x52,
	0x60, 0xd4, 0x60, 0x0a, 0x82, 0x70, 0x92, 0xd8, 0xc0, 0xda, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x58, 0xf5, 0x6f, 0x7c, 0x54, 0x00, 0x00, 0x00,
}
